services:
  win-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: win-monitor
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - win-monitor-data:/app/server/data

volumes:
  win-monitor-data:
